name: arrow_framework
version: 1.0.0
homepage: https://www.github.com/deriegle/dart_arrow_framework
description: A friendly API framework for Dart

environment: 
  sdk: '>=2.8.1 <3.0.0'

dependencies: 
  body_parser: ^1.1.1
  http_parser: ^3.1.4
  path_to_regexp: ^0.3.0
  arrow_framework_orm: ^1.0.0

dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4
  mock_request: ^1.0.7

dependency_overrides: 
  arrow_framework_orm: 
    path: ../arrow_framework_orm
  arrow_framework_open_api_generator: 
    path: ../arrow_framework_open_api_generator
